### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-leveldown#250]
Ref https://github.com/Level/community/issues/34.

**Comment by vweevers** [comment]
We need to increase the max body size in airtap:

```
PayloadTooLargeError: request entity too large
    at readStream (D:\Projecten\GitHub\Level\abstract-leveldown\node_modules\raw-body\index.js:155:17)
    at getRawBody (D:\Projecten\GitHub\Level\abstract-leveldown\node_modules\raw-body\index.js:108:12)
    at read (D:\Projecten\GitHub\Level\abstract-leveldown\node_modules\body-parser\lib\read.js:77:3)
    at jsonParser (D:\Projecten\GitHub\Level\abstract-leveldown\node_modules\body-parser\lib\types\json.js:135:5)
    at Layer.handle [as handle_request] (D:\Projecten\GitHub\Level\abstract-leveldown\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Projecten\GitHub\Level\abstract-leveldown\node_modules\express\lib\router\index.js:317:13)
    at D:\Projecten\GitHub\Level\abstract-leveldown\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\Projecten\GitHub\Level\abstract-leveldown\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Projecten\GitHub\Level\abstract-leveldown\node_modules\express\lib\router\index.js:275:10)
    at compression (D:\Projecten\GitHub\Level\abstract-leveldown\node_modules\compression\index.js:220:5)
```

**Comment by vweevers** [comment]
Should we exclude `abstract/*` from coverage? Only implementations can achieve 100% coverage.

![image](https://user-images.githubusercontent.com/3055345/42375861-3f69bffa-811d-11e8-9fcc-d3a4f91c26af.png)

Also, when we add code coverage to implementations, we should check that `abstract` is *not* excluded (due to it being in `node_modules`).

**Comment by ralphtheninja** [comment]
> Should we exclude abstract/* from coverage? Only implementations can achieve 100% coverage.

Makes sense.

**Comment by vweevers** [comment]
Excluding works differently in [nyc](https://www.npmjs.com/package/nyc#excluding-files) (node tests) and [browserify-instanbul](https://github.com/devongovett/browserify-istanbul#usage) (browser tests). In addition, because `browserify-instanbul` is a transform controlled by airtap, airtap has to set the ignore option. Hm.

**Comment by vweevers** [comment]
Well, heh, one option is to rename `abstract/` to `test/`, so that it matches the default ignore options 😄
